require('plugins.configs.cmp')
require('plugins.configs.lualine')
require('plugins.configs.treesitter')
require('plugins.configs.lsp-config')
require('plugins.configs.presence')
require('plugins.configs.alpha')
